@baseUrl = http://localhost:3000/api

### GET /api - 404
GET {{baseUrl}}

### GET /api/does-not-exist - 404
GET {{baseUrl}}/does-not-exist

###
GET {{baseUrl}}/entries

###
POST {{baseUrl}}/entries
Content-Type: application/json

{
  "text": "Hello",
  "author": "Sven",
  "date": ""
}

### TOGGLE MARK-AS-DONE
PATCH {{baseUrl}}/entries/mark-as-done
Content-Type: application/json

{
  "_id":""
}

### DELETE
DELETE {{baseUrl}}/entries
Content-Type: application/json

{
  "_id":""
}